config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end
  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end
    unauthenticated do
      root 'users#index', as: :unauthenticated_root
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    can :create, [Comment, Post]

    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Comment, author: user
      can :destroy, Post, author: user
    end
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_post_comment_counter
  after_destroy :decrement_post_comment_counter

  def update_post_comment_counter
    post.increment!(:commentscounter)
  end

  def decrement_post_comment_counter
    post.decrement!(:commentscounter)
  end
  private :update_post_comment_counter, :decrement_post_comment_counter
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  belongs_to :post

  after_save :update_post_like_counter
  def update_post_like_counter
    post.increment!(:likescounter)
  end
  private :update_post_like_counter
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :commentscounter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likescounter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  after_save :update_user_post_counter
  after_destroy :decrement_user_post_counter

  def update_user_post_counter
    author.increment!(:postscounter)
  end

  def decrement_user_post_counter
    author.decrement!(:postscounter)
  end

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
  private :update_user_post_counter, :decrement_user_post_counter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
  validates :postscounter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def most_three_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = %i[name photo bio role]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def index
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    respond_to do |format|
      format.json { render json: @comments }
      format.json { render json: @posts }
    end
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = @user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to request.referrer, notice: 'comment was successfully created.' }
        format.json { render Json: @comment, status: :created }
      else
        format.html { render :new }
        format.json do
          render json: @comment, status: :created
        end
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referrer
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new
    @like.author = @user
    if @like.save
      redirect_to user_post_path(@user, @post)
    else
      redirect_to request.referrer
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)

    respond_to do |format|
      format.html
      format.xml { render xml: @posts }
      format.json { render json: @posts }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html
      format.xml { render xml: @posts.comments }
      format.json { render json: @posts.comments }
    end
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out_and_redirect
    else
      find_user
    end
  end

  private

  def sign_out_and_redirect
    sign_out current_user
    redirect_to new_user_session_path
  end

  def find_user
    @user = User.find_by(id: params[:id])
    redirect_to users_path, alert: 'User not found' unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_with model:[current_user, @post, Comment.new], url:user_post_comments_path(current_user, @post) do |form| %>
  <div class="comment_form">
    <div>
      <%= form.label :comment%><br>
      <%= form.text_area :text, class:'comment_input' %>
      <% form.object.errors.full_messages_for(:text).each do |message|%>
        <div><%= message %></div>
      <%end%>
    </div>
    <br>
    <%= form.submit class:'post_button' %>
  </div>
<%end%>

app/views/comments/new.html.erb
<%= render "form", post:@post%>
<%= render "form", comment:@comment%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'style', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% flash.each do |key, message| %>
      <div class="flash-message">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: [@user, @post, Like.new], url: user_post_likes_path(User.find(params[:user_id]), @post), method: :post) do |form| %>
  <div class="like_form">
    <%= form.submit "Like", class: 'post_button' %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: [@current_user, @current_user.posts.build] do |form| %>
    <div class="post_form">
    <h3> Add New Post </h3>
      <div>
      <%= form.label :title  %><br>
      <%= form.text_field :title, class:'post_title'%>
      <% form.object.errors.full_messages_for(:title).each do |message|%>
      <div><%= message %></div>
      <%end%>
    </div>
      <br>
     <div>
       <%= form.label :text%><br>
        <%= form.text_area :text, class:'post_text'%>
        <% form.object.errors.full_messages_for(:text).each do |message|%>
        <div><%= message %></div>
        <%end%>
     </div>
     <br>
      <%= form.submit "Create Post", class:"post_button"%>
    </div>
<%end%>

app/views/posts/index.html copy.erb
<h1>list of posts for a given user </h1>

app/views/posts/index.html.erb
<%= render 'shared/user', user:@user%>
<div class="post_list">
  <% @posts.includes(:comments, :author).each do |post| %>
    <%= render 'shared/post', post:post %>
    <% if  !post.five_most_recent_comments.includes(:author).empty?%>
      <div class ="post_comment">
        <%post.five_most_recent_comments.includes(:author).each do |comment| %>
          <%= render 'shared/comment', comment:comment %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="button_holder">
  <button>Pagination</button>
  <button><%= link_to 'Back', :back %></button>
</div>

app/views/posts/new.html.erb
<%= render "form", post:@post%>

app/views/posts/show.html.erb
<div class="post_detail">
  <div class="post_detail_card">
    <div class="post_detail_card_header">
      <p class ="post_title_card"> Post # <%=@post.id%> by <%=@post.author.name%></p>
      <p>Comments: <%=@post.commentscounter%> Likes: <%=@post.likescounter%></p>
    </div>
    <div>
      <p><%=@post.text%></p>
    </div>
  </div>
  <% if  !@post.comments.empty?%>
    <div class ="post_detail_comment">
      <% @post.comments.includes(:author).each do |comment| %>
        <%= render 'shared/comment', comment:comment %>
      <% end %>
    </div>
  <%end%>
  <div class="comment_like_holder">
    <div class= "comment_form_holder">
      <h3>Leave a comment</h3>
      <%= render 'comments/form', comment: @comment %>
    </div>
    <div class="like_form_holder">
      <h3>Like this post</h3>
      <%= render 'likes/form', like: @like %>
    </div>
  </div>
  <div class="button_holder">
  <% if can? :destroy, @post%>
    <button>
      <%= link_to 'Delete post', user_post_path(@user,@post), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
    </button>
  <% end %>
</div>

app/views/shared/_comment.html.erb
<p><span>Username:</span><%=comment.author.name %>
  <span>Comment:</span><%=comment.text %>
  <% if can? :destroy, comment %>
  <turbo-frame id="comment-frame">
  <%= turbo_frame_tag 'comment-frame' do %>
    <%= form_with url: user_post_comment_path(@user, comment.post, comment.id), method: :delete, data: { turbo_frame: '_top' } do |form| %>
      <%= form.submit 'X', data: { turbo_confirm: "Are you sure?" } %>
    <% end %>
  <% end %>
</turbo-frame>
  <% end %>
</p>

app/views/shared/_post.html.erb
<div class= "post_card">
<h4>
 <%= link_to "Post ##{post.id }", "/users/#{@user.id}/posts/#{post.id}" %>
 </h4>
      <p> <%= post.title %> </p>
      <p class="post_counter"><span>comments: <%=post.commentscounter%> </span>
       <span>Likes: <%=post.likescounter%> </span>
       </p>
</div>

app/views/shared/_user.html.erb
<div class= "user">
 <div class="user_card">
<div class="user_card_image">
<img class="image-placeholder"src="<%= user.photo %>" alt="add-image"/>
</div>
 <div class="user_card_detail">
<h2><%= link_to user.name, user %></h2>
<p>Number of posts: <%= user.postscounter %></p>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="sign_out_button">
  <button>
    <%= link_to 'Sign out',  destroy_user_session_path, method: :delete %>
  </button>
</div>
<% @users.each do |user| %>
  <%= render 'shared/user', user:user%>
<%end%>
<div class="button_holder">
  <button>
    <%= link_to 'Create new post', new_user_post_path(current_user)%>
  </button>
</div>

app/views/users/show.html.erb
<%= render 'shared/user', user:@user%>

<div class="user_bio">
 <h3>Bio</h3>
 <p><%= @user.bio %><p>
</div>

<div class="user_post">
   <% @user.most_three_recent_post.each do |post| %>

      <%= render 'shared/post', post:post %>
   <%end%>

</div>
<div class="button_holder">
<button>
 <%= link_to 'See all posts', user_posts_path(@user,@posts) %>
</button>
<button>
 <%= link_to 'Back', :back %>
</button>
</div>